import { POI, RouteOption, StreetSegment, MunicipalTicket } from '@/types';

// Realistic city map coordinate space (normalized 0-800 x 0-600 for high resolution SVG rendering)
export const CITY_BOUNDS = {
  minX: 50,
  maxX: 750,
  minY: 40,
  maxY: 560,
  baseLat: 12.9830,
  baseLng: 80.2590,
};

export const INITIAL_USER_POS = {
  x: 140,
  y: 440,
  lat: 12.9782,
  lng: 80.2514,
  label: 'Thiruvanmiyur Bus Terminal',
};

export const DEFAULT_DESTINATION_POS = {
  x: 660,
  y: 120,
  lat: 12.9895,
  lng: 80.2642,
  label: 'Besant Nagar Residential Enclave',
};

export const SAMPLE_POIS: POI[] = [
  {
    id: 'poi-1',
    name: 'MedPlus 24/7 Emergency Pharmacy',
    category: 'pharmacy',
    address: '42, Dr MGR Main Road, Thiruvanmiyur',
    distanceKm: 0.35,
    walkingTimeMinutes: 4,
    isOpen: true,
    hours: 'Open 24/7',
    x: 230,
    y: 390,
    lat: 12.9801,
    lng: 80.2530,
    phone: '+91 44 2441 0982',
    isSafeShelter: true,
    description: 'Well-lit CCTV premise with 24-hour security guard and emergency first-aid.',
  },
  {
    id: 'poi-2',
    name: 'J2 Police Station (All-Women Help Desk)',
    category: 'police',
    address: 'Lattice Bridge Road Junction, Adyar',
    distanceKm: 0.75,
    walkingTimeMinutes: 8,
    isOpen: true,
    hours: 'Open 24/7 (Patrol Active)',
    x: 380,
    y: 280,
    lat: 12.9825,
    lng: 80.2562,
    phone: '112 / +91 44 2491 0100',
    isSafeShelter: true,
    description: 'Designated 24/7 safe zone with pink patrol vehicle and quick response unit.',
  },
  {
    id: 'poi-3',
    name: 'Apollo Speciality Emergency Centre',
    category: 'hospital',
    address: 'LB Road, Adyar',
    distanceKm: 1.1,
    walkingTimeMinutes: 13,
    isOpen: true,
    hours: 'Emergency Trauma Open 24/7',
    x: 480,
    y: 210,
    lat: 12.9848,
    lng: 80.2595,
    phone: '1066 / +91 44 2491 5500',
    isSafeShelter: true,
    description: 'Full medical trauma ward, continuous bright illumination, guarded entrance.',
  },
  {
    id: 'poi-4',
    name: '24/7 Nilgiris Supermarket & Safe Point',
    category: 'store',
    address: '15, Beach Avenue, Besant Nagar',
    distanceKm: 0.6,
    walkingTimeMinutes: 7,
    isOpen: true,
    hours: 'Open 24 Hours',
    x: 520,
    y: 340,
    lat: 12.9832,
    lng: 80.2610,
    phone: '+91 44 2490 1283',
    isSafeShelter: true,
    description: 'Active staff on site, high customer footfall, brightly lit storefront.',
  },
  {
    id: 'poi-5',
    name: 'Corner Bakery & Cafe',
    category: 'store',
    address: '2nd Cross Street, Ward 175',
    distanceKm: 0.85,
    walkingTimeMinutes: 10,
    isOpen: false,
    hours: 'Closed at 10:00 PM',
    x: 320,
    y: 470,
    lat: 12.9775,
    lng: 80.2550,
    phone: '+91 44 2445 6789',
    isSafeShelter: false,
    description: 'Currently closed. Shutters down and street lights dim in this section.',
  },
  {
    id: 'poi-6',
    name: 'Bharat Petroleum 24/7 Station & Booth',
    category: 'shelter',
    address: 'Corner of ECR & East Coast Avenue',
    distanceKm: 1.4,
    walkingTimeMinutes: 16,
    isOpen: true,
    hours: 'Open 24/7 (Staffed)',
    x: 620,
    y: 260,
    lat: 12.9865,
    lng: 80.2635,
    phone: '+91 44 2448 9911',
    isSafeShelter: true,
    description: 'Floodlit petrol station, emergency water, panic assistance button on premise.',
  },
  {
    id: 'poi-7',
    name: 'Thiruvanmiyur MRTS Station & CISF Post',
    category: 'station',
    address: 'Kamaraj Nagar West',
    distanceKm: 1.6,
    walkingTimeMinutes: 18,
    isOpen: true,
    hours: 'Open till 11:45 PM',
    x: 180,
    y: 220,
    lat: 12.9850,
    lng: 80.2480,
    phone: '+91 44 2452 4000',
    isSafeShelter: true,
    description: 'Security guards at token concourse, active CCTV corridor.',
  },
];

export const CITY_STREET_SEGMENTS: StreetSegment[] = [
  // Primary Arterials (Well Lit)
  {
    id: 'seg-1',
    name: 'Dr MGR Main Road (Northbound)',
    x1: 140,
    y1: 440,
    x2: 260,
    y2: 360,
    roadClass: 'primary',
    streetLightsCount: 24,
    streetLightsWorking: 24,
    isLit: true,
    frontageScore: 0.95,
    footpathScore: 0.90,
    riskScore: 12,
    ward: 'Ward 175 (Thiruvanmiyur)',
    lampsNeededToFix: 0,
  },
  {
    id: 'seg-2',
    name: 'Lattice Bridge Road (South Corridors)',
    x1: 260,
    y1: 360,
    x2: 400,
    y2: 260,
    roadClass: 'primary',
    streetLightsCount: 30,
    streetLightsWorking: 29,
    isLit: true,
    frontageScore: 0.92,
    footpathScore: 0.85,
    riskScore: 14,
    ward: 'Ward 173 (Adyar)',
    lampsNeededToFix: 1,
  },
  {
    id: 'seg-3',
    name: 'Beach Avenue Boulevard',
    x1: 400,
    y1: 260,
    x2: 560,
    y2: 170,
    roadClass: 'primary',
    streetLightsCount: 28,
    streetLightsWorking: 28,
    isLit: true,
    frontageScore: 0.88,
    footpathScore: 0.92,
    riskScore: 10,
    ward: 'Ward 176 (Besant Nagar)',
    lampsNeededToFix: 0,
  },
  {
    id: 'seg-4',
    name: 'Residential Link Enclave',
    x1: 560,
    y1: 170,
    x2: 660,
    y2: 120,
    roadClass: 'residential',
    streetLightsCount: 16,
    streetLightsWorking: 15,
    isLit: true,
    frontageScore: 0.80,
    footpathScore: 0.80,
    riskScore: 15,
    ward: 'Ward 176 (Besant Nagar)',
    lampsNeededToFix: 1,
  },

  // Moderate segments
  {
    id: 'seg-5',
    name: 'Kamaraj Nagar 3rd Cross',
    x1: 140,
    y1: 440,
    x2: 300,
    y2: 430,
    roadClass: 'secondary',
    streetLightsCount: 18,
    streetLightsWorking: 15,
    isLit: true,
    frontageScore: 0.65,
    footpathScore: 0.70,
    riskScore: 28,
    ward: 'Ward 175 (Thiruvanmiyur)',
    lampsNeededToFix: 3,
  },
  {
    id: 'seg-6',
    name: 'Customs Colony Lane',
    x1: 300,
    y1: 430,
    x2: 490,
    y2: 300,
    roadClass: 'secondary',
    streetLightsCount: 22,
    streetLightsWorking: 19,
    isLit: true,
    frontageScore: 0.70,
    footpathScore: 0.65,
    riskScore: 24,
    ward: 'Ward 173 (Adyar)',
    lampsNeededToFix: 3,
  },
  {
    id: 'seg-7',
    name: 'Damodarapuram Bypass',
    x1: 490,
    y1: 300,
    x2: 660,
    y2: 120,
    roadClass: 'secondary',
    streetLightsCount: 26,
    streetLightsWorking: 22,
    isLit: true,
    frontageScore: 0.75,
    footpathScore: 0.75,
    riskScore: 22,
    ward: 'Ward 176 (Besant Nagar)',
    lampsNeededToFix: 4,
  },

  // Dangerous / Unlit Alleyway Segments (Dark Spots)
  {
    id: 'seg-8',
    name: 'Old Canal Service Alley (CRITICAL DARK SPOT)',
    x1: 140,
    y1: 440,
    x2: 350,
    y2: 280,
    roadClass: 'alley',
    streetLightsCount: 18,
    streetLightsWorking: 3,
    isLit: false,
    frontageScore: 0.15,
    footpathScore: 0.20,
    riskScore: 88,
    ward: 'Ward 175 (Thiruvanmiyur)',
    lampsNeededToFix: 15,
  },
  {
    id: 'seg-9',
    name: 'Unlit Drainage Boundary Stretch (HIGH DANGER)',
    x1: 350,
    y1: 280,
    x2: 520,
    y2: 190,
    roadClass: 'alley',
    streetLightsCount: 14,
    streetLightsWorking: 1,
    isLit: false,
    frontageScore: 0.10,
    footpathScore: 0.10,
    riskScore: 92,
    ward: 'Ward 173 (Adyar)',
    lampsNeededToFix: 13,
  },
  {
    id: 'seg-10',
    name: 'Marshland Overpass Dead-End Lane',
    x1: 520,
    y1: 190,
    x2: 660,
    y2: 120,
    roadClass: 'alley',
    streetLightsCount: 12,
    streetLightsWorking: 4,
    isLit: false,
    frontageScore: 0.25,
    footpathScore: 0.30,
    riskScore: 78,
    ward: 'Ward 176 (Besant Nagar)',
    lampsNeededToFix: 8,
  },

  // Direct fast segment
  {
    id: 'seg-11',
    name: 'Indira Nagar Diagonal Cut',
    x1: 260,
    y1: 360,
    x2: 490,
    y2: 300,
    roadClass: 'secondary',
    streetLightsCount: 16,
    streetLightsWorking: 12,
    isLit: true,
    frontageScore: 0.60,
    footpathScore: 0.60,
    riskScore: 36,
    ward: 'Ward 173 (Adyar)',
    lampsNeededToFix: 4,
  },
];

export const FOUR_ROUTE_OPTIONS: RouteOption[] = [
  {
    id: 'route-safest',
    mode: 'safest',
    name: 'Safest Route',
    title: 'Illuminated Commercial & Safe-Point Corridor',
    durationMinutes: 28,
    distanceKm: 2.4,
    safetyScore: 95,
    unlitMeters: 0,
    litPercentage: 98,
    description:
      'Continuous bright LED streetlights, passes 24/7 MedPlus, J2 Police Station, Apollo Hospital & Nilgiris. Active pedestrian footfall & CCTV.',
    pathCoordinates: [
      [140, 440],
      [200, 400],
      [260, 360],
      [330, 310],
      [400, 260],
      [480, 210],
      [560, 170],
      [610, 140],
      [660, 120],
    ],
    streetNames: [
      'Dr MGR Main Road (North)',
      'Lattice Bridge Road',
      'Beach Avenue Boulevard',
      'Besant Nagar Main Enclave',
    ],
    alertWarnings: [
      'Verified Safe Corridor: 100% of streetlights functional',
      '2 Verified Safe Havens within 200m at all times',
    ],
    openShopsCount: 14,
    policeStationsNearby: 1,
  },
  {
    id: 'route-fastest',
    mode: 'fastest',
    name: 'Fastest Route',
    title: 'Direct Arterial Diagonal Cut',
    durationMinutes: 21,
    distanceKm: 1.8,
    safetyScore: 74,
    unlitMeters: 140,
    litPercentage: 78,
    description:
      'Shortest walking time. Travels along Dr MGR Road then cuts through Indira Nagar Diagonal and Damodarapuram.',
    pathCoordinates: [
      [140, 440],
      [260, 360],
      [375, 330],
      [490, 300],
      [580, 210],
      [660, 120],
    ],
    streetNames: [
      'Dr MGR Main Road',
      'Indira Nagar Diagonal Cut',
      'Damodarapuram Bypass',
      'Besant Nagar Avenue',
    ],
    alertWarnings: [
      'Moderate lighting: 140m stretch near Indira Nagar has 4 non-functioning lamps',
      'Fewer open shops after 10 PM on diagonal cut',
    ],
    openShopsCount: 6,
    policeStationsNearby: 1,
  },
  {
    id: 'route-moderate',
    mode: 'moderate',
    name: 'Moderate Route',
    title: 'Balanced Residential Link',
    durationMinutes: 25,
    distanceKm: 2.1,
    safetyScore: 84,
    unlitMeters: 85,
    litPercentage: 86,
    description:
      'Avoids dense traffic while maintaining 86% streetlight coverage through Kamaraj Nagar & Customs Colony.',
    pathCoordinates: [
      [140, 440],
      [220, 435],
      [300, 430],
      [400, 360],
      [490, 300],
      [580, 210],
      [660, 120],
    ],
    streetNames: [
      'Kamaraj Nagar 3rd Cross',
      'Customs Colony Lane',
      'Damodarapuram Bypass',
      'Besant Nagar Enclave',
    ],
    alertWarnings: [
      'Good residential lighting; slightly quieter between 11 PM - 5 AM',
      'Passed Corner Bakery (closed) and 24/7 Nilgiris',
    ],
    openShopsCount: 9,
    policeStationsNearby: 0,
  },
  {
    id: 'route-dangerous',
    mode: 'dangerous',
    name: 'Most Dangerous Route',
    title: 'UNLIT CANAL ALLEYWAY (AVOID)',
    durationMinutes: 19,
    distanceKm: 1.6,
    safetyScore: 26,
    unlitMeters: 520,
    litPercentage: 38,
    description:
      'HIGH DANGER PROFILE: Narrow, isolated canal service road with 28 broken streetlights, zero open commercial frontage, and dead-end blind spots.',
    pathCoordinates: [
      [140, 440],
      [240, 360],
      [350, 280],
      [430, 235],
      [520, 190],
      [590, 155],
      [660, 120],
    ],
    streetNames: [
      'Old Canal Service Alley',
      'Unlit Drainage Boundary Stretch',
      'Marshland Overpass Dead-End',
    ],
    alertWarnings: [
      'CRITICAL: 520 meters in total darkness (broken municipal lamps)',
      'Zero open shops or witnesses after 8:00 PM',
      'Blind corners and high historical incident risk (score 88/100)',
      'NIZHAL advises taking the Safest Route (+7 mins saves life)',
    ],
    openShopsCount: 0,
    policeStationsNearby: 0,
  },
];

export const INITIAL_MUNICIPAL_TICKETS: MunicipalTicket[] = [
  {
    id: 'TICK-1092',
    title: '15 Streetlights Out on Old Canal Service Alley',
    ward: 'Ward 175 (Thiruvanmiyur)',
    locationName: 'Old Canal Alley between Dr MGR Rd & Drainage boundary',
    lat: 12.9798,
    lng: 80.2541,
    reason: 'Underground cable fault + 15 vandalized sodium fixtures causing 320m pitch-black blind spot.',
    priority: 'critical',
    status: 'open',
    reportedAt: 'Today, 09:15 AM',
    fixedLampsNeeded: 15,
    riskReductionScore: 62,
  },
  {
    id: 'TICK-1093',
    title: 'Drainage Boundary Dark Corridor Repair',
    ward: 'Ward 173 (Adyar)',
    locationName: 'Drainage Boundary Road near bridge span',
    lat: 12.9818,
    lng: 80.2575,
    reason: '13 high-pressure bulbs broken, high pedestrian hazard reported by night workers.',
    priority: 'critical',
    status: 'open',
    reportedAt: 'Yesterday, 11:40 PM',
    fixedLampsNeeded: 13,
    riskReductionScore: 58,
  },
  {
    id: 'TICK-1094',
    title: 'Flickering LED Mast on Lattice Bridge Road',
    ward: 'Ward 173 (Adyar)',
    locationName: 'LB Road opposite J2 Police outpost',
    lat: 12.9822,
    lng: 80.2568,
    reason: 'Power surge intermittent flickering on 1 LED pole.',
    priority: 'medium',
    status: 'dispatched',
    reportedAt: 'Today, 07:30 AM',
    fixedLampsNeeded: 1,
    riskReductionScore: 8,
    dispatchedTo: 'Crew Alpha (Vehicle TN-07-G-4412)',
  },
  {
    id: 'TICK-1095',
    title: 'Indira Nagar Diagonal Cut Lighting Enhancement',
    ward: 'Ward 173 (Adyar)',
    locationName: 'Indira Nagar 2nd Avenue crossing',
    lat: 12.9839,
    lng: 80.2582,
    reason: '4 bulbs dimmed below standard lumens, creates shadowed sidewalk.',
    priority: 'high',
    status: 'open',
    reportedAt: 'Yesterday, 06:15 PM',
    fixedLampsNeeded: 4,
    riskReductionScore: 24,
  },
];
